[package]
name = "bentobox"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bento"
path = "src/bin/bento_cli.rs"


[dependencies]
anyhow = "1.0.89"
axum = "0.8.1"
block2 = "0.6.0"
bus = "2.4.1"
clap = { version = "4.5.16", features = ["derive"] }
crossbeam = "0.8.4"
ctrlc = "3.4.5"
eyre = "0.6.12"
futures-io = { version = "0.2.0-beta" }
libc = "0.2.169"
objc2 = { version = "0.6.0", features = ["catch-all", "exception"] }
objc2-app-kit = { version = "0.3.0", features = ["NSApplication", "NSRunningApplication", "NSWindow", "NSGraphics", "NSMenu", "NSMenuItem"]}
objc2-foundation = { version = "0.3.0", features = ["NSString", "NSArray", "NSKeyValueObserving", "NSThread", "NSPathUtilities"] }
objc2-virtualization = { version = "0.3.0", features = ["default"] }
reqwest = { version = "0.12.8", features = ["stream", "blocking"] }
serde = "1.0.217"
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio", "chrono"] }
tokio = { version = "1", features = ["full"] }
